import { MODULE_IDS } from '../modules/moduleRegistry.js';
import { PRODUCT_MODE_IDS, PRODUCT_MODE_LABELS } from './productModes.js';

export const PRODUCT_MODE_METADATA = Object.freeze({
  [PRODUCT_MODE_IDS.STAFF_APPRAISAL]: Object.freeze({
    id: PRODUCT_MODE_IDS.STAFF_APPRAISAL,
    label: PRODUCT_MODE_LABELS[PRODUCT_MODE_IDS.STAFF_APPRAISAL],
    shortLabel: 'Staff',
    description: 'Internal appraisal operations for staff appraisal companies.',
    primaryEntity: 'Appraisal shops and staff appraiser companies',
    primaryExperience: 'Internal order operations',
    primaryDailyQuestion:
      'What orders need attention today, who owns them, and what is blocking delivery?',
    dashboardName: 'Staff Operations Dashboard',
    includedModules: Object.freeze([
      MODULE_IDS.CORE_WORKSPACE,
      MODULE_IDS.DASHBOARD,
      MODULE_IDS.NOTIFICATIONS,
      MODULE_IDS.ACTIVITY,
      MODULE_IDS.SETTINGS,
      MODULE_IDS.ORDERS,
      MODULE_IDS.CLIENTS,
      MODULE_IDS.TEAM_ACCESS,
      MODULE_IDS.REVIEWS,
      MODULE_IDS.CALENDAR,
    ]),
    optionalModules: Object.freeze([
      MODULE_IDS.ASSIGNMENTS,
      MODULE_IDS.RELATIONSHIPS,
      MODULE_IDS.VENDOR_PORTAL,
      MODULE_IDS.CLIENT_PORTAL,
      MODULE_IDS.REPORTS,
      MODULE_IDS.ANALYTICS,
      MODULE_IDS.AI_WORKSPACE,
      MODULE_IDS.BILLING,
      MODULE_IDS.INTEGRATIONS,
      MODULE_IDS.ONBOARDING,
      MODULE_IDS.TENANT_ADMIN,
    ]),
    hiddenByDefaultModules: Object.freeze([
      MODULE_IDS.AMC_OPERATIONS,
      MODULE_IDS.VENDOR_PORTAL,
      MODULE_IDS.CLIENT_PORTAL,
      MODULE_IDS.BILLING,
      MODULE_IDS.INTEGRATIONS,
    ]),
    futureNavShape: Object.freeze([
      'Dashboard',
      'Orders',
      'Calendar',
      'Clients',
      'Team Access',
      'Reports / Analytics',
      'Settings',
    ]),
    futureDashboardSections: Object.freeze([
      'Active order attention queue',
      'Due soon / overdue orders',
      'Appraiser workload',
      'Reviewer workload',
      'Calendar pressure',
      'Recent operational activity',
    ]),
    upgradePaths: Object.freeze([
      'Continental AMC Panel',
      'Client Portal',
      'Analytics',
      'AI',
      'Reports',
      'Integrations',
    ]),
  }),
  [PRODUCT_MODE_IDS.AMC_OPERATIONS]: Object.freeze({
    id: PRODUCT_MODE_IDS.AMC_OPERATIONS,
    label: PRODUCT_MODE_LABELS[PRODUCT_MODE_IDS.AMC_OPERATIONS],
    shortLabel: 'AMC',
    description: 'Network operations for AMCs and appraisal management teams.',
    primaryEntity: 'AMCs and appraisal management teams',
    primaryExperience: 'Vendor/client/order network operations',
    primaryDailyQuestion:
      'Which client orders need intake, assignment, vendor follow-up, review, or SLA escalation?',
    dashboardName: 'AMC Network Operations Dashboard',
    includedModules: Object.freeze([
      MODULE_IDS.CORE_WORKSPACE,
      MODULE_IDS.DASHBOARD,
      MODULE_IDS.NOTIFICATIONS,
      MODULE_IDS.ACTIVITY,
      MODULE_IDS.SETTINGS,
      MODULE_IDS.ORDERS,
      MODULE_IDS.CLIENTS,
      MODULE_IDS.ASSIGNMENTS,
      MODULE_IDS.RELATIONSHIPS,
      MODULE_IDS.REVIEWS,
      MODULE_IDS.CALENDAR,
      MODULE_IDS.AMC_OPERATIONS,
    ]),
    optionalModules: Object.freeze([
      MODULE_IDS.VENDOR_PORTAL,
      MODULE_IDS.CLIENT_PORTAL,
      MODULE_IDS.REPORTS,
      MODULE_IDS.ANALYTICS,
      MODULE_IDS.AI_WORKSPACE,
      MODULE_IDS.BILLING,
      MODULE_IDS.INTEGRATIONS,
      MODULE_IDS.ONBOARDING,
      MODULE_IDS.TENANT_ADMIN,
    ]),
    hiddenByDefaultModules: Object.freeze([
      MODULE_IDS.VENDOR_PORTAL,
      MODULE_IDS.CLIENT_PORTAL,
      MODULE_IDS.TEAM_ACCESS,
    ]),
    futureNavShape: Object.freeze([
      'AMC Dashboard',
      'Orders / Intake',
      'Assignments',
      'Vendor Panel',
      'Clients / Lenders',
      'Reviews / QC',
      'Calendar / SLA',
      'Analytics',
      'Integrations',
      'Settings',
    ]),
    futureDashboardSections: Object.freeze([
      'Intake / unassigned orders',
      'Vendor offer and acceptance queue',
      'Active assignment SLA pressure',
      'Review / QC queue',
      'Client/lender exception queue',
      'Vendor follow-up and escalation queue',
    ]),
    upgradePaths: Object.freeze([
      'Vendor Portal',
      'Client Portal',
      'Analytics',
      'AI',
      'Billing',
      'Integrations',
    ]),
  }),
  [PRODUCT_MODE_IDS.VENDOR_PORTAL]: Object.freeze({
    id: PRODUCT_MODE_IDS.VENDOR_PORTAL,
    label: PRODUCT_MODE_LABELS[PRODUCT_MODE_IDS.VENDOR_PORTAL],
    shortLabel: 'Vendor',
    description: 'Assignment-only packet execution for external vendors.',
    primaryEntity: 'External appraisers and vendor companies',
    primaryExperience: 'Assigned work packet execution',
    primaryDailyQuestion:
      'What assigned packets do I need to accept, work, update, or submit?',
    dashboardName: 'Assignment Packet Dashboard',
    includedModules: Object.freeze([
      MODULE_IDS.CORE_WORKSPACE,
      MODULE_IDS.DASHBOARD,
      MODULE_IDS.NOTIFICATIONS,
      MODULE_IDS.ACTIVITY,
      MODULE_IDS.SETTINGS,
      MODULE_IDS.ASSIGNMENTS,
      MODULE_IDS.VENDOR_PORTAL,
      MODULE_IDS.CALENDAR,
    ]),
    optionalModules: Object.freeze([
      MODULE_IDS.ORDERS,
      MODULE_IDS.CLIENTS,
      MODULE_IDS.TEAM_ACCESS,
      MODULE_IDS.REPORTS,
      MODULE_IDS.AI_WORKSPACE,
    ]),
    hiddenByDefaultModules: Object.freeze([
      MODULE_IDS.ORDERS,
      MODULE_IDS.CLIENTS,
      MODULE_IDS.AMC_OPERATIONS,
      MODULE_IDS.CLIENT_PORTAL,
      MODULE_IDS.ANALYTICS,
      MODULE_IDS.BILLING,
      MODULE_IDS.INTEGRATIONS,
      MODULE_IDS.TENANT_ADMIN,
    ]),
    futureNavShape: Object.freeze([
      'My Assignments',
      'Due Soon',
      'Revisions',
      'Messages / Updates',
      'Completed Work',
      'Profile / Availability',
      'Settings',
    ]),
    futureDashboardSections: Object.freeze([
      'New offers',
      'Active assignments',
      'Due soon / overdue packets',
      'Revision requests',
      'Submitted/completed packet history',
    ]),
    upgradePaths: Object.freeze(['Staff Appraisal Mode', 'AI/report assistance']),
  }),
  [PRODUCT_MODE_IDS.CLIENT_PORTAL]: Object.freeze({
    id: PRODUCT_MODE_IDS.CLIENT_PORTAL,
    label: PRODUCT_MODE_LABELS[PRODUCT_MODE_IDS.CLIENT_PORTAL],
    shortLabel: 'Client',
    description: 'Request, status, document, report, and message workspace for clients.',
    primaryEntity: 'Lenders, direct clients, and requester organizations',
    primaryExperience: 'Order request and status visibility',
    primaryDailyQuestion:
      'What requests need my attention, what is their status, and what reports or documents are available?',
    dashboardName: 'Client Order Status Dashboard',
    includedModules: Object.freeze([
      MODULE_IDS.CORE_WORKSPACE,
      MODULE_IDS.DASHBOARD,
      MODULE_IDS.NOTIFICATIONS,
      MODULE_IDS.ACTIVITY,
      MODULE_IDS.SETTINGS,
      MODULE_IDS.CLIENT_PORTAL,
      MODULE_IDS.REPORTS,
      MODULE_IDS.ORDERS,
    ]),
    optionalModules: Object.freeze([
      MODULE_IDS.BILLING,
      MODULE_IDS.INTEGRATIONS,
      MODULE_IDS.ANALYTICS,
      MODULE_IDS.TEAM_ACCESS,
    ]),
    hiddenByDefaultModules: Object.freeze([
      MODULE_IDS.CLIENTS,
      MODULE_IDS.ASSIGNMENTS,
      MODULE_IDS.REVIEWS,
      MODULE_IDS.AMC_OPERATIONS,
      MODULE_IDS.VENDOR_PORTAL,
    ]),
    futureNavShape: Object.freeze([
      'Submit Request',
      'My Requests',
      'Status Updates',
      'Documents / Reports',
      'Messages / Updates',
      'Organization Users',
      'Billing',
      'Settings',
    ]),
    futureDashboardSections: Object.freeze([
      'Active Requests',
      'Waiting on Me',
      'Recent Updates',
      'Delivered Reports / Documents',
      'Communication History',
    ]),
    upgradePaths: Object.freeze(['Integrations', 'Analytics', 'Billing', 'Reporting']),
  }),
  [PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM]: Object.freeze({
    id: PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM,
    label: PRODUCT_MODE_LABELS[PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM],
    shortLabel: 'Hybrid',
    description: 'Combined internal operations and network participation with lane separation.',
    primaryEntity: 'Companies with multiple operational roles',
    primaryExperience: 'Internal operations plus selected network lanes',
    primaryDailyQuestion:
      'What internal work and network work need attention, and which lane owns the next action?',
    dashboardName: 'Ecosystem Operations Dashboard',
    includedModules: Object.freeze([
      MODULE_IDS.CORE_WORKSPACE,
      MODULE_IDS.DASHBOARD,
      MODULE_IDS.NOTIFICATIONS,
      MODULE_IDS.ACTIVITY,
      MODULE_IDS.SETTINGS,
    ]),
    optionalModules: Object.freeze([
      MODULE_IDS.ORDERS,
      MODULE_IDS.CLIENTS,
      MODULE_IDS.TEAM_ACCESS,
      MODULE_IDS.ASSIGNMENTS,
      MODULE_IDS.REVIEWS,
      MODULE_IDS.CALENDAR,
      MODULE_IDS.RELATIONSHIPS,
      MODULE_IDS.AMC_OPERATIONS,
      MODULE_IDS.VENDOR_PORTAL,
      MODULE_IDS.CLIENT_PORTAL,
      MODULE_IDS.REPORTS,
      MODULE_IDS.ANALYTICS,
      MODULE_IDS.AI_WORKSPACE,
      MODULE_IDS.BILLING,
      MODULE_IDS.INTEGRATIONS,
      MODULE_IDS.ONBOARDING,
      MODULE_IDS.TENANT_ADMIN,
    ]),
    hiddenByDefaultModules: Object.freeze([]),
    futureNavShape: Object.freeze([
      'Internal Operations',
      'Network Work',
      'Sent Assignments',
      'Relationships',
      'Clients / Portals',
      'Intelligence',
      'Administration',
    ]),
    futureDashboardSections: Object.freeze([
      'Internal Operations lane',
      'Network Work lane',
      'Sent Assignments lane',
      'Relationship Attention lane',
      'Client/Portal lane',
    ]),
    upgradePaths: Object.freeze(['AMC', 'Vendor', 'Client', 'AI', 'Analytics', 'Integrations']),
  }),
});

export const PRODUCT_MODE_METADATA_LIST = Object.freeze(
  Object.values(PRODUCT_MODE_METADATA),
);
