export const PERMISSIONS = Object.freeze({
  COMPANY_READ: "company.read",
  COMPANY_UPDATE_PROFILE: "company.update_profile",
  COMPANY_MANAGE_BRANDING: "company.manage_branding",
  COMPANY_MANAGE_LOCATIONS: "company.manage_locations",
  COMPANY_MANAGE_INTEGRATIONS: "company.manage_integrations",
  COMPANY_MANAGE_SECURITY: "company.manage_security",
  COMPANY_TRANSFER_OWNERSHIP: "company.transfer_ownership",
  COMPANY_DELETE_OR_DEACTIVATE: "company.delete_or_deactivate",

  USERS_READ: "users.read",
  USERS_INVITE: "users.invite",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_DEACTIVATE: "users.deactivate",
  USERS_RESET_MFA: "users.reset_mfa",
  USERS_MANAGE_COMPANY_ACCESS: "users.manage_company_access",
  USERS_GRANT_OWNER: "users.grant_owner",
  USERS_REVOKE_OWNER: "users.revoke_owner",

  ROLES_READ: "roles.read",
  ROLES_CREATE: "roles.create",
  ROLES_UPDATE: "roles.update",
  ROLES_DELETE: "roles.delete",
  ROLES_ASSIGN: "roles.assign",
  ROLES_MANAGE_PERMISSIONS: "roles.manage_permissions",
  ROLES_MANAGE_OWNER_ROLE: "roles.manage_owner_role",
  ROLES_DELETE_SYSTEM_ROLE: "roles.delete_system_role",

  CLIENTS_CREATE: "clients.create",
  CLIENTS_READ_ASSIGNED: "clients.read.assigned",
  CLIENTS_READ_ALL: "clients.read.all",
  CLIENTS_UPDATE_ASSIGNED: "clients.update.assigned",
  CLIENTS_UPDATE_ALL: "clients.update.all",
  CLIENTS_DELETE: "clients.delete",
  CLIENTS_ARCHIVE: "clients.archive",

  ORDERS_CREATE: "orders.create",
  ORDERS_READ_ASSIGNED: "orders.read.assigned",
  ORDERS_READ_ALL: "orders.read.all",
  ORDERS_UPDATE_ASSIGNED: "orders.update.assigned",
  ORDERS_UPDATE_ALL: "orders.update.all",
  ORDERS_DELETE: "orders.delete",
  ORDERS_ARCHIVE: "orders.archive",
  ORDERS_EXPORT: "orders.export",

  ASSIGNMENTS_READ: "assignments.read",
  ASSIGNMENTS_ASSIGN_APPRAISER: "assignments.assign_appraiser",
  ASSIGNMENTS_ASSIGN_REVIEWER: "assignments.assign_reviewer",
  ASSIGNMENTS_ASSIGN_INSPECTOR: "assignments.assign_inspector",
  ASSIGNMENTS_ASSIGN_BILLING: "assignments.assign_billing",
  ASSIGNMENTS_REASSIGN: "assignments.reassign",
  ASSIGNMENTS_CLEAR: "assignments.clear",

  WORKFLOW_STATUS_SUBMIT_TO_REVIEW: "workflow.status.submit_to_review",
  WORKFLOW_STATUS_REQUEST_REVISIONS: "workflow.status.request_revisions",
  WORKFLOW_STATUS_RESUBMIT: "workflow.status.resubmit",
  WORKFLOW_STATUS_APPROVE_REVIEW: "workflow.status.approve_review",
  WORKFLOW_STATUS_READY_FOR_CLIENT: "workflow.status.ready_for_client",
  WORKFLOW_STATUS_DELIVER_TO_CLIENT: "workflow.status.deliver_to_client",
  WORKFLOW_STATUS_COMPLETE: "workflow.status.complete",
  WORKFLOW_STATUS_REOPEN: "workflow.status.reopen",
  WORKFLOW_OVERRIDE_STATUS: "workflow.override_status",

  ACTIVITY_READ_ASSIGNED: "activity.read.assigned",
  ACTIVITY_READ_ALL: "activity.read.all",
  ACTIVITY_CREATE_NOTE_ASSIGNED: "activity.create.note.assigned",
  ACTIVITY_CREATE_NOTE_ALL: "activity.create.note.all",
  ACTIVITY_CREATE_SYSTEM_EVENT: "activity.create.system_event",
  ACTIVITY_EDIT_OWN_NOTE: "activity.edit_own_note",
  ACTIVITY_DELETE_OWN_NOTE: "activity.delete_own_note",
  ACTIVITY_MODERATE: "activity.moderate",

  COMMUNICATIONS_VIEW_ASSIGNED: "communications.view.assigned",
  COMMUNICATIONS_VIEW_ALL: "communications.view.all",
  COMMUNICATIONS_REPLY_ASSIGNED: "communications.reply.assigned",
  COMMUNICATIONS_REPLY_ALL: "communications.reply.all",
  COMMUNICATIONS_TAG_USERS: "communications.tag_users",
  COMMUNICATIONS_MARK_IMPORTANT: "communications.mark_important",

  NOTIFICATIONS_READ_OWN: "notifications.read_own",
  NOTIFICATIONS_MARK_READ_OWN: "notifications.mark_read_own",
  NOTIFICATIONS_PREFERENCES_MANAGE_OWN: "notifications.preferences.manage_own",
  NOTIFICATIONS_PREFERENCES_MANAGE_COMPANY: "notifications.preferences.manage_company",
  NOTIFICATIONS_SEND_MANUAL: "notifications.send_manual",
  NOTIFICATIONS_AUDIT_DELIVERY: "notifications.audit_delivery",

  DOCUMENTS_UPLOAD_ASSIGNED: "documents.upload.assigned",
  DOCUMENTS_UPLOAD_ALL: "documents.upload.all",
  DOCUMENTS_READ_ASSIGNED: "documents.read.assigned",
  DOCUMENTS_READ_ALL: "documents.read.all",
  DOCUMENTS_DELETE: "documents.delete",
  DOCUMENTS_PUBLISH_TO_CLIENT: "documents.publish_to_client",

  BILLING_READ: "billing.read",
  BILLING_UPDATE: "billing.update",
  BILLING_INVOICE_CREATE: "billing.invoice.create",
  BILLING_INVOICE_SEND: "billing.invoice.send",
  BILLING_PAYMENT_RECORD: "billing.payment.record",
  BILLING_EXPORT: "billing.export",
  BILLING_MANAGE_RATES: "billing.manage_rates",
  BILLING_MANAGE_SUBSCRIPTION: "billing.manage_subscription",

  REPORTS_VIEW_OPERATIONS: "reports.view_operations",
  REPORTS_VIEW_REVIEW_QUEUE: "reports.view_review_queue",
  REPORTS_VIEW_APPRAISER_PERFORMANCE: "reports.view_appraiser_performance",
  REPORTS_VIEW_BILLING: "reports.view_billing",
  REPORTS_EXPORT: "reports.export",

  SETTINGS_VIEW: "settings.view",
  SETTINGS_MANAGE_WORKFLOW: "settings.manage_workflow",
  SETTINGS_MANAGE_NOTIFICATIONS: "settings.manage_notifications",
  SETTINGS_MANAGE_TEMPLATES: "settings.manage_templates",
  SETTINGS_MANAGE_AUTHENTICATION: "settings.manage_authentication",
  SETTINGS_MANAGE_DATA_RETENTION: "settings.manage_data_retention",
  SETTINGS_MANAGE_INTEGRATIONS_SECRETS: "settings.manage_integrations.secrets",

  NAVIGATION_DASHBOARD_VIEW: "navigation.dashboard.view",
  NAVIGATION_ORDERS_VIEW: "navigation.orders.view",
  NAVIGATION_CLIENTS_VIEW: "navigation.clients.view",
  NAVIGATION_USERS_VIEW: "navigation.users.view",
  NAVIGATION_REPORTS_VIEW: "navigation.reports.view",
  NAVIGATION_BILLING_VIEW: "navigation.billing.view",
  NAVIGATION_SETTINGS_VIEW: "navigation.settings.view",
});

export const ALL_PERMISSION_KEYS = Object.freeze(Object.values(PERMISSIONS));

