import { PRODUCT_MODE_IDS } from '../productModes/productModes.js';
import { MODULE_CATEGORY_IDS } from './moduleCategories.js';

export const MODULE_IDS = Object.freeze({
  CORE_WORKSPACE: 'core_workspace',
  DASHBOARD: 'dashboard',
  NOTIFICATIONS: 'notifications',
  ACTIVITY: 'activity',
  SETTINGS: 'settings',
  ORDERS: 'orders',
  CLIENTS: 'clients',
  TEAM_ACCESS: 'team_access',
  ASSIGNMENTS: 'assignments',
  REVIEWS: 'reviews',
  CALENDAR: 'calendar',
  REPORTS: 'reports',
  ANALYTICS: 'analytics',
  AI_WORKSPACE: 'ai_workspace',
  RELATIONSHIPS: 'relationships',
  AMC_OPERATIONS: 'amc_operations',
  VENDOR_PORTAL: 'vendor_portal',
  CLIENT_PORTAL: 'client_portal',
  BILLING: 'billing',
  INTEGRATIONS: 'integrations',
  ONBOARDING: 'onboarding',
  TENANT_ADMIN: 'tenant_admin',
});

export const MODULE_IMPLEMENTATION_STATUS = Object.freeze({
  CURRENT: 'current',
  PARTIAL: 'partial',
  FUTURE: 'future',
});

export const MODULE_BUNDLE_TYPES = Object.freeze({
  SYSTEM: 'system',
  REQUIRED: 'required',
  OPTIONAL: 'optional',
  DEPENDENT: 'dependent',
  PREMIUM: 'premium',
});

export const NAV_REGISTRATION_KINDS = Object.freeze({
  PRIMARY: 'primary',
  SECONDARY: 'secondary',
  CONTEXTUAL: 'contextual',
  HIDDEN_UNTIL_COMPOSED: 'hidden_until_composed',
});

export const DASHBOARD_REGISTRATION_KINDS = Object.freeze({
  SHELL: 'shell',
  SECTION: 'section',
  WIDGET: 'widget',
  EMPTY_STATE: 'empty_state',
  HIDDEN_UNTIL_COMPOSED: 'hidden_until_composed',
});

const ALL_PRODUCT_MODES = Object.freeze([
  PRODUCT_MODE_IDS.STAFF_APPRAISAL,
  PRODUCT_MODE_IDS.AMC_OPERATIONS,
  PRODUCT_MODE_IDS.VENDOR_PORTAL,
  PRODUCT_MODE_IDS.CLIENT_PORTAL,
  PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM,
]);

const STAFF_AND_AMC_MODES = Object.freeze([
  PRODUCT_MODE_IDS.STAFF_APPRAISAL,
  PRODUCT_MODE_IDS.AMC_OPERATIONS,
  PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM,
]);

const createFutureRegistrationShape = (kind, ownerModuleId, notes) =>
  Object.freeze({
    kind,
    ownerModuleId,
    registrationStatus: 'metadata_only',
    runtimeComposed: false,
    notes,
  });

export const MODULE_REGISTRY = Object.freeze({
  [MODULE_IDS.CORE_WORKSPACE]: Object.freeze({
    id: MODULE_IDS.CORE_WORKSPACE,
    label: 'Core Workspace',
    category: MODULE_CATEGORY_IDS.SYSTEM,
    status: MODULE_IMPLEMENTATION_STATUS.PARTIAL,
    bundleType: MODULE_BUNDLE_TYPES.SYSTEM,
    defaultProductModes: ALL_PRODUCT_MODES,
    dependencies: Object.freeze([]),
    permissionDomains: Object.freeze(['core.*', 'core.dashboard.view', 'settings.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.HIDDEN_UNTIL_COMPOSED,
      MODULE_IDS.CORE_WORKSPACE,
      'Future app shell, account, and company-context registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.HIDDEN_UNTIL_COMPOSED,
      MODULE_IDS.CORE_WORKSPACE,
      'Delegates to the dashboard module once runtime composition exists.',
    ),
  }),
  [MODULE_IDS.DASHBOARD]: Object.freeze({
    id: MODULE_IDS.DASHBOARD,
    label: 'Dashboard',
    category: MODULE_CATEGORY_IDS.SYSTEM,
    status: MODULE_IMPLEMENTATION_STATUS.CURRENT,
    bundleType: MODULE_BUNDLE_TYPES.SYSTEM,
    defaultProductModes: ALL_PRODUCT_MODES,
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE]),
    permissionDomains: Object.freeze(['core.dashboard.view']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.PRIMARY,
      MODULE_IDS.DASHBOARD,
      'Future mode-specific dashboard nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.SHELL,
      MODULE_IDS.DASHBOARD,
      'Future resolver chooses Staff, AMC, Vendor, Client, or Hybrid dashboard shells.',
    ),
  }),
  [MODULE_IDS.NOTIFICATIONS]: Object.freeze({
    id: MODULE_IDS.NOTIFICATIONS,
    label: 'Notifications',
    category: MODULE_CATEGORY_IDS.SYSTEM,
    status: MODULE_IMPLEMENTATION_STATUS.CURRENT,
    bundleType: MODULE_BUNDLE_TYPES.SYSTEM,
    defaultProductModes: ALL_PRODUCT_MODES,
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE]),
    permissionDomains: Object.freeze(['notifications.*', 'notifications.preferences.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.CONTEXTUAL,
      MODULE_IDS.NOTIFICATIONS,
      'Future notification bell/preferences registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.WIDGET,
      MODULE_IDS.NOTIFICATIONS,
      'Future unread/action-required widget registration shape only.',
    ),
  }),
  [MODULE_IDS.ACTIVITY]: Object.freeze({
    id: MODULE_IDS.ACTIVITY,
    label: 'Activity',
    category: MODULE_CATEGORY_IDS.SYSTEM,
    status: MODULE_IMPLEMENTATION_STATUS.CURRENT,
    bundleType: MODULE_BUNDLE_TYPES.SYSTEM,
    defaultProductModes: ALL_PRODUCT_MODES,
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE]),
    permissionDomains: Object.freeze(['activity.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.SECONDARY,
      MODULE_IDS.ACTIVITY,
      'Future mode-safe activity nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.WIDGET,
      MODULE_IDS.ACTIVITY,
      'Future mode-safe recent activity widget registration shape only.',
    ),
  }),
  [MODULE_IDS.SETTINGS]: Object.freeze({
    id: MODULE_IDS.SETTINGS,
    label: 'Settings',
    category: MODULE_CATEGORY_IDS.SYSTEM,
    status: MODULE_IMPLEMENTATION_STATUS.CURRENT,
    bundleType: MODULE_BUNDLE_TYPES.SYSTEM,
    defaultProductModes: ALL_PRODUCT_MODES,
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE]),
    permissionDomains: Object.freeze(['settings.*', 'notifications.preferences.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.SECONDARY,
      MODULE_IDS.SETTINGS,
      'Future personal/company settings nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.HIDDEN_UNTIL_COMPOSED,
      MODULE_IDS.SETTINGS,
      'Settings should not create dashboard clutter by default.',
    ),
  }),
  [MODULE_IDS.ORDERS]: Object.freeze({
    id: MODULE_IDS.ORDERS,
    label: 'Orders',
    category: MODULE_CATEGORY_IDS.CORE_OPERATIONS,
    status: MODULE_IMPLEMENTATION_STATUS.CURRENT,
    bundleType: MODULE_BUNDLE_TYPES.REQUIRED,
    defaultProductModes: STAFF_AND_AMC_MODES,
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE, MODULE_IDS.DASHBOARD]),
    permissionDomains: Object.freeze(['orders.*', 'workflow.status.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.PRIMARY,
      MODULE_IDS.ORDERS,
      'Future internal order operations nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.SECTION,
      MODULE_IDS.ORDERS,
      'Future owned-order queue/dashboard section registration shape only.',
    ),
  }),
  [MODULE_IDS.CLIENTS]: Object.freeze({
    id: MODULE_IDS.CLIENTS,
    label: 'Clients',
    category: MODULE_CATEGORY_IDS.CORE_OPERATIONS,
    status: MODULE_IMPLEMENTATION_STATUS.CURRENT,
    bundleType: MODULE_BUNDLE_TYPES.REQUIRED,
    defaultProductModes: STAFF_AND_AMC_MODES,
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE]),
    permissionDomains: Object.freeze(['clients.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.PRIMARY,
      MODULE_IDS.CLIENTS,
      'Future internal client/AMC CRM nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.WIDGET,
      MODULE_IDS.CLIENTS,
      'Future client/lender operational widget registration shape only.',
    ),
  }),
  [MODULE_IDS.TEAM_ACCESS]: Object.freeze({
    id: MODULE_IDS.TEAM_ACCESS,
    label: 'Team Access',
    category: MODULE_CATEGORY_IDS.CORE_OPERATIONS,
    status: MODULE_IMPLEMENTATION_STATUS.CURRENT,
    bundleType: MODULE_BUNDLE_TYPES.REQUIRED,
    defaultProductModes: Object.freeze([
      PRODUCT_MODE_IDS.STAFF_APPRAISAL,
      PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM,
    ]),
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE, MODULE_IDS.SETTINGS]),
    permissionDomains: Object.freeze(['users/team.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.PRIMARY,
      MODULE_IDS.TEAM_ACCESS,
      'Future team invitation and role administration nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.EMPTY_STATE,
      MODULE_IDS.TEAM_ACCESS,
      'Future setup/reminder registration shape only.',
    ),
  }),
  [MODULE_IDS.ASSIGNMENTS]: Object.freeze({
    id: MODULE_IDS.ASSIGNMENTS,
    label: 'Assignments',
    category: MODULE_CATEGORY_IDS.NETWORK_ECOSYSTEM,
    status: MODULE_IMPLEMENTATION_STATUS.PARTIAL,
    bundleType: MODULE_BUNDLE_TYPES.REQUIRED,
    defaultProductModes: Object.freeze([
      PRODUCT_MODE_IDS.AMC_OPERATIONS,
      PRODUCT_MODE_IDS.VENDOR_PORTAL,
      PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM,
    ]),
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE, MODULE_IDS.DASHBOARD]),
    permissionDomains: Object.freeze(['assignments.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.PRIMARY,
      MODULE_IDS.ASSIGNMENTS,
      'Future assignment packet nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.SECTION,
      MODULE_IDS.ASSIGNMENTS,
      'Future owner-side sent assignments and assigned-company packet dashboard shape only.',
    ),
  }),
  [MODULE_IDS.REVIEWS]: Object.freeze({
    id: MODULE_IDS.REVIEWS,
    label: 'Reviews',
    category: MODULE_CATEGORY_IDS.CORE_OPERATIONS,
    status: MODULE_IMPLEMENTATION_STATUS.PARTIAL,
    bundleType: MODULE_BUNDLE_TYPES.REQUIRED,
    defaultProductModes: STAFF_AND_AMC_MODES,
    dependencies: Object.freeze([MODULE_IDS.ORDERS]),
    permissionDomains: Object.freeze(['reviews.*', 'workflow.status.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.PRIMARY,
      MODULE_IDS.REVIEWS,
      'Future review/QC nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.SECTION,
      MODULE_IDS.REVIEWS,
      'Future review queue widget registration shape only.',
    ),
  }),
  [MODULE_IDS.CALENDAR]: Object.freeze({
    id: MODULE_IDS.CALENDAR,
    label: 'Calendar',
    category: MODULE_CATEGORY_IDS.CORE_OPERATIONS,
    status: MODULE_IMPLEMENTATION_STATUS.CURRENT,
    bundleType: MODULE_BUNDLE_TYPES.REQUIRED,
    defaultProductModes: Object.freeze([
      PRODUCT_MODE_IDS.STAFF_APPRAISAL,
      PRODUCT_MODE_IDS.AMC_OPERATIONS,
      PRODUCT_MODE_IDS.VENDOR_PORTAL,
      PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM,
    ]),
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE]),
    permissionDomains: Object.freeze(['calendar.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.PRIMARY,
      MODULE_IDS.CALENDAR,
      'Future mode-specific calendar nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.WIDGET,
      MODULE_IDS.CALENDAR,
      'Future calendar pressure/assigned-work widget registration shape only.',
    ),
  }),
  [MODULE_IDS.REPORTS]: Object.freeze({
    id: MODULE_IDS.REPORTS,
    label: 'Reports',
    category: MODULE_CATEGORY_IDS.INTELLIGENCE,
    status: MODULE_IMPLEMENTATION_STATUS.FUTURE,
    bundleType: MODULE_BUNDLE_TYPES.OPTIONAL,
    defaultProductModes: Object.freeze([
      PRODUCT_MODE_IDS.STAFF_APPRAISAL,
      PRODUCT_MODE_IDS.AMC_OPERATIONS,
      PRODUCT_MODE_IDS.CLIENT_PORTAL,
      PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM,
    ]),
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE]),
    permissionDomains: Object.freeze(['reports.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.SECONDARY,
      MODULE_IDS.REPORTS,
      'Future reports/documents nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.WIDGET,
      MODULE_IDS.REPORTS,
      'Future reports/documents widget registration shape only.',
    ),
  }),
  [MODULE_IDS.ANALYTICS]: Object.freeze({
    id: MODULE_IDS.ANALYTICS,
    label: 'Analytics',
    category: MODULE_CATEGORY_IDS.INTELLIGENCE,
    status: MODULE_IMPLEMENTATION_STATUS.PARTIAL,
    bundleType: MODULE_BUNDLE_TYPES.PREMIUM,
    defaultProductModes: Object.freeze([
      PRODUCT_MODE_IDS.STAFF_APPRAISAL,
      PRODUCT_MODE_IDS.AMC_OPERATIONS,
      PRODUCT_MODE_IDS.CLIENT_PORTAL,
      PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM,
    ]),
    dependencies: Object.freeze([MODULE_IDS.DASHBOARD]),
    permissionDomains: Object.freeze(['analytics.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.SECONDARY,
      MODULE_IDS.ANALYTICS,
      'Future analytics nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.WIDGET,
      MODULE_IDS.ANALYTICS,
      'Future mode-safe analytics widget registration shape only.',
    ),
  }),
  [MODULE_IDS.AI_WORKSPACE]: Object.freeze({
    id: MODULE_IDS.AI_WORKSPACE,
    label: 'AI Workspace',
    category: MODULE_CATEGORY_IDS.INTELLIGENCE,
    status: MODULE_IMPLEMENTATION_STATUS.FUTURE,
    bundleType: MODULE_BUNDLE_TYPES.PREMIUM,
    defaultProductModes: Object.freeze([
      PRODUCT_MODE_IDS.STAFF_APPRAISAL,
      PRODUCT_MODE_IDS.AMC_OPERATIONS,
      PRODUCT_MODE_IDS.VENDOR_PORTAL,
      PRODUCT_MODE_IDS.CLIENT_PORTAL,
      PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM,
    ]),
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE]),
    permissionDomains: Object.freeze(['ai.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.CONTEXTUAL,
      MODULE_IDS.AI_WORKSPACE,
      'Future contextual AI registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.WIDGET,
      MODULE_IDS.AI_WORKSPACE,
      'Future AI summary widget registration shape only.',
    ),
  }),
  [MODULE_IDS.RELATIONSHIPS]: Object.freeze({
    id: MODULE_IDS.RELATIONSHIPS,
    label: 'Relationships',
    category: MODULE_CATEGORY_IDS.NETWORK_ECOSYSTEM,
    status: MODULE_IMPLEMENTATION_STATUS.PARTIAL,
    bundleType: MODULE_BUNDLE_TYPES.OPTIONAL,
    defaultProductModes: Object.freeze([
      PRODUCT_MODE_IDS.AMC_OPERATIONS,
      PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM,
    ]),
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE]),
    permissionDomains: Object.freeze(['relationships.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.PRIMARY,
      MODULE_IDS.RELATIONSHIPS,
      'Future relationship lifecycle nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.SECTION,
      MODULE_IDS.RELATIONSHIPS,
      'Future relationship attention widget registration shape only.',
    ),
  }),
  [MODULE_IDS.AMC_OPERATIONS]: Object.freeze({
    id: MODULE_IDS.AMC_OPERATIONS,
    label: 'AMC Operations',
    category: MODULE_CATEGORY_IDS.NETWORK_ECOSYSTEM,
    status: MODULE_IMPLEMENTATION_STATUS.FUTURE,
    bundleType: MODULE_BUNDLE_TYPES.REQUIRED,
    defaultProductModes: Object.freeze([
      PRODUCT_MODE_IDS.AMC_OPERATIONS,
      PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM,
    ]),
    dependencies: Object.freeze([
      MODULE_IDS.ORDERS,
      MODULE_IDS.CLIENTS,
      MODULE_IDS.ASSIGNMENTS,
      MODULE_IDS.RELATIONSHIPS,
    ]),
    permissionDomains: Object.freeze(['amc.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.PRIMARY,
      MODULE_IDS.AMC_OPERATIONS,
      'Future AMC command-center nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.SHELL,
      MODULE_IDS.AMC_OPERATIONS,
      'Future AMC Network Operations Dashboard registration shape only.',
    ),
  }),
  [MODULE_IDS.VENDOR_PORTAL]: Object.freeze({
    id: MODULE_IDS.VENDOR_PORTAL,
    label: 'Vendor Portal',
    category: MODULE_CATEGORY_IDS.NETWORK_ECOSYSTEM,
    status: MODULE_IMPLEMENTATION_STATUS.PARTIAL,
    bundleType: MODULE_BUNDLE_TYPES.REQUIRED,
    defaultProductModes: Object.freeze([
      PRODUCT_MODE_IDS.VENDOR_PORTAL,
      PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM,
    ]),
    dependencies: Object.freeze([MODULE_IDS.ASSIGNMENTS]),
    permissionDomains: Object.freeze(['vendor.*', 'assignments.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.PRIMARY,
      MODULE_IDS.VENDOR_PORTAL,
      'Future Vendor Portal packet nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.SHELL,
      MODULE_IDS.VENDOR_PORTAL,
      'Future Assignment Packet Dashboard registration shape only.',
    ),
  }),
  [MODULE_IDS.CLIENT_PORTAL]: Object.freeze({
    id: MODULE_IDS.CLIENT_PORTAL,
    label: 'Client Portal',
    category: MODULE_CATEGORY_IDS.NETWORK_ECOSYSTEM,
    status: MODULE_IMPLEMENTATION_STATUS.FUTURE,
    bundleType: MODULE_BUNDLE_TYPES.REQUIRED,
    defaultProductModes: Object.freeze([
      PRODUCT_MODE_IDS.CLIENT_PORTAL,
      PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM,
    ]),
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE, MODULE_IDS.DASHBOARD]),
    permissionDomains: Object.freeze(['client_portal.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.PRIMARY,
      MODULE_IDS.CLIENT_PORTAL,
      'Future Client Portal request/status nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.SHELL,
      MODULE_IDS.CLIENT_PORTAL,
      'Future Client Order Status Dashboard registration shape only.',
    ),
  }),
  [MODULE_IDS.BILLING]: Object.freeze({
    id: MODULE_IDS.BILLING,
    label: 'Billing',
    category: MODULE_CATEGORY_IDS.PLATFORM_ADMIN,
    status: MODULE_IMPLEMENTATION_STATUS.FUTURE,
    bundleType: MODULE_BUNDLE_TYPES.PREMIUM,
    defaultProductModes: ALL_PRODUCT_MODES,
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE, MODULE_IDS.SETTINGS]),
    permissionDomains: Object.freeze(['billing.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.SECONDARY,
      MODULE_IDS.BILLING,
      'Future billing nav registration shape only; no billing enforcement in this slice.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.WIDGET,
      MODULE_IDS.BILLING,
      'Future billing status widget registration shape only.',
    ),
  }),
  [MODULE_IDS.INTEGRATIONS]: Object.freeze({
    id: MODULE_IDS.INTEGRATIONS,
    label: 'Integrations',
    category: MODULE_CATEGORY_IDS.PLATFORM_ADMIN,
    status: MODULE_IMPLEMENTATION_STATUS.FUTURE,
    bundleType: MODULE_BUNDLE_TYPES.PREMIUM,
    defaultProductModes: Object.freeze([
      PRODUCT_MODE_IDS.STAFF_APPRAISAL,
      PRODUCT_MODE_IDS.AMC_OPERATIONS,
      PRODUCT_MODE_IDS.CLIENT_PORTAL,
      PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM,
    ]),
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE, MODULE_IDS.SETTINGS]),
    permissionDomains: Object.freeze(['integrations.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.SECONDARY,
      MODULE_IDS.INTEGRATIONS,
      'Future integrations nav registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.WIDGET,
      MODULE_IDS.INTEGRATIONS,
      'Future integration health widget registration shape only.',
    ),
  }),
  [MODULE_IDS.ONBOARDING]: Object.freeze({
    id: MODULE_IDS.ONBOARDING,
    label: 'Onboarding',
    category: MODULE_CATEGORY_IDS.PLATFORM_ADMIN,
    status: MODULE_IMPLEMENTATION_STATUS.FUTURE,
    bundleType: MODULE_BUNDLE_TYPES.DEPENDENT,
    defaultProductModes: ALL_PRODUCT_MODES,
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE]),
    permissionDomains: Object.freeze(['onboarding.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.CONTEXTUAL,
      MODULE_IDS.ONBOARDING,
      'Future guided setup registration shape only; no onboarding UI in this slice.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.EMPTY_STATE,
      MODULE_IDS.ONBOARDING,
      'Future setup progress widget registration shape only.',
    ),
  }),
  [MODULE_IDS.TENANT_ADMIN]: Object.freeze({
    id: MODULE_IDS.TENANT_ADMIN,
    label: 'Tenant Administration',
    category: MODULE_CATEGORY_IDS.PLATFORM_ADMIN,
    status: MODULE_IMPLEMENTATION_STATUS.FUTURE,
    bundleType: MODULE_BUNDLE_TYPES.DEPENDENT,
    defaultProductModes: Object.freeze([PRODUCT_MODE_IDS.HYBRID_ECOSYSTEM]),
    dependencies: Object.freeze([MODULE_IDS.CORE_WORKSPACE, MODULE_IDS.SETTINGS]),
    permissionDomains: Object.freeze(['tenant_admin.*', 'settings.*']),
    navRegistration: createFutureRegistrationShape(
      NAV_REGISTRATION_KINDS.SECONDARY,
      MODULE_IDS.TENANT_ADMIN,
      'Future tenant/company module administration registration shape only.',
    ),
    dashboardRegistration: createFutureRegistrationShape(
      DASHBOARD_REGISTRATION_KINDS.HIDDEN_UNTIL_COMPOSED,
      MODULE_IDS.TENANT_ADMIN,
      'Tenant administration should not create dashboard clutter by default.',
    ),
  }),
});

export const MODULE_REGISTRY_LIST = Object.freeze(Object.values(MODULE_REGISTRY));
export const MODULE_ID_LIST = Object.freeze(Object.keys(MODULE_REGISTRY));
