begin;

create table if not exists public.client_contacts (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  name text not null,
  title text,
  email text,
  phone text,
  notes text,
  status text not null default 'active',
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by_user_id uuid,
  constraint client_contacts_name_required check (length(trim(name)) > 0),
  constraint client_contacts_status_check check (status in ('active', 'inactive'))
);

create index if not exists idx_client_contacts_company_client
  on public.client_contacts(company_id, client_id, status, is_default desc, name);

create unique index if not exists uq_client_contacts_one_default_per_client
  on public.client_contacts(company_id, client_id)
  where is_default is true and status = 'active';

drop trigger if exists trg_client_contacts_updated_at on public.client_contacts;
create trigger trg_client_contacts_updated_at
before update on public.client_contacts
for each row execute function public.update_updated_at_column();

alter table public.client_contacts enable row level security;

drop policy if exists "client_contacts_read_visible_clients" on public.client_contacts;
create policy "client_contacts_read_visible_clients"
on public.client_contacts
for select
using (
  public.current_app_user_can_read_client_row(company_id, client_id)
);

revoke all on public.client_contacts from public, anon;
grant select on public.client_contacts to authenticated;

alter table public.orders
  add column if not exists client_contact_id bigint null,
  add column if not exists client_contact_name text null,
  add column if not exists client_contact_title text null,
  add column if not exists client_contact_email text null,
  add column if not exists client_contact_phone text null;

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conname = 'orders_client_contact_id_fkey'
       and conrelid = 'public.orders'::regclass
  ) then
    alter table public.orders
      add constraint orders_client_contact_id_fkey
      foreign key (client_contact_id)
      references public.client_contacts(id)
      on delete set null;
  end if;
end;
$$;

create index if not exists idx_orders_client_contact_id
  on public.orders(client_contact_id)
  where client_contact_id is not null;

create or replace function public.rpc_client_contact_list(
  p_client_id bigint
)
returns table (
  contact_id bigint,
  company_id uuid,
  client_id bigint,
  name text,
  title text,
  email text,
  phone text,
  notes text,
  status text,
  is_default boolean,
  created_at timestamptz,
  updated_at timestamptz,
  created_by_user_id uuid
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid := public.current_app_user_id();
  v_company_id uuid := public.current_company_id();
  v_client_company_id uuid;
begin
  if v_actor_user_id is null then
    raise exception 'app_user_not_found'
      using errcode = '42501';
  end if;

  if v_company_id is null or not public.current_app_user_has_current_company() then
    raise exception 'current_company_membership_required'
      using errcode = '42501';
  end if;

  select coalesce(c.company_id, public.default_company_id())
    into v_client_company_id
    from public.clients c
   where c.id = p_client_id;

  if not found or v_client_company_id <> v_company_id then
    raise exception 'client_not_found'
      using errcode = 'P0002';
  end if;

  if not public.current_app_user_can_read_client_row(v_client_company_id, p_client_id) then
    raise exception 'client_contact_read_permission_required'
      using errcode = '42501';
  end if;

  return query
  select
    cc.id as contact_id,
    cc.company_id,
    cc.client_id,
    cc.name,
    cc.title,
    cc.email,
    cc.phone,
    cc.notes,
    cc.status,
    cc.is_default,
    cc.created_at,
    cc.updated_at,
    cc.created_by_user_id
  from public.client_contacts cc
  where cc.company_id = v_company_id
    and cc.client_id = p_client_id
  order by
    case when cc.status = 'active' then 0 else 1 end,
    cc.is_default desc,
    cc.name asc,
    cc.id asc;
end;
$$;

create or replace function public.rpc_client_contact_create(
  p_client_id bigint,
  p_contact jsonb
)
returns table (
  contact_id bigint,
  company_id uuid,
  client_id bigint,
  name text,
  title text,
  email text,
  phone text,
  notes text,
  status text,
  is_default boolean,
  created_at timestamptz,
  updated_at timestamptz,
  created_by_user_id uuid
)
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid := public.current_app_user_id();
  v_company_id uuid := public.current_company_id();
  v_client_company_id uuid;
  v_name text := trim(coalesce(p_contact->>'name', ''));
  v_status text := lower(trim(coalesce(p_contact->>'status', 'active')));
  v_is_default boolean := coalesce((p_contact->>'is_default')::boolean, false);
  v_contact_id bigint;
begin
  if v_actor_user_id is null then
    raise exception 'app_user_not_found'
      using errcode = '42501';
  end if;

  if v_company_id is null or not public.current_app_user_has_current_company() then
    raise exception 'current_company_membership_required'
      using errcode = '42501';
  end if;

  select coalesce(c.company_id, public.default_company_id())
    into v_client_company_id
    from public.clients c
   where c.id = p_client_id;

  if not found or v_client_company_id <> v_company_id then
    raise exception 'client_not_found'
      using errcode = 'P0002';
  end if;

  if not public.current_app_user_can_update_client_row(v_client_company_id, p_client_id) then
    raise exception 'client_contact_write_permission_required'
      using errcode = '42501';
  end if;

  if v_name = '' then
    raise exception 'client_contact_name_required'
      using errcode = '22023';
  end if;

  if v_status not in ('active', 'inactive') then
    raise exception 'invalid_client_contact_status'
      using errcode = '22023';
  end if;

  if v_is_default and v_status = 'active' then
    update public.client_contacts
       set is_default = false
     where company_id = v_company_id
       and client_id = p_client_id
       and is_default is true;
  end if;

  insert into public.client_contacts (
    company_id,
    client_id,
    name,
    title,
    email,
    phone,
    notes,
    status,
    is_default,
    created_by_user_id
  )
  values (
    v_company_id,
    p_client_id,
    v_name,
    nullif(p_contact->>'title', ''),
    nullif(p_contact->>'email', ''),
    nullif(p_contact->>'phone', ''),
    nullif(p_contact->>'notes', ''),
    v_status,
    case when v_status = 'active' then v_is_default else false end,
    v_actor_user_id
  )
  returning id into v_contact_id;

  return query
  select *
    from public.rpc_client_contact_list(p_client_id) listed
   where listed.contact_id = v_contact_id;
end;
$$;

create or replace function public.rpc_client_contact_update(
  p_contact_id bigint,
  p_patch jsonb
)
returns table (
  contact_id bigint,
  company_id uuid,
  client_id bigint,
  name text,
  title text,
  email text,
  phone text,
  notes text,
  status text,
  is_default boolean,
  created_at timestamptz,
  updated_at timestamptz,
  created_by_user_id uuid
)
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid := public.current_app_user_id();
  v_company_id uuid := public.current_company_id();
  v_contact public.client_contacts%rowtype;
  v_name text;
  v_status text;
  v_is_default boolean;
begin
  if v_actor_user_id is null then
    raise exception 'app_user_not_found'
      using errcode = '42501';
  end if;

  if v_company_id is null or not public.current_app_user_has_current_company() then
    raise exception 'current_company_membership_required'
      using errcode = '42501';
  end if;

  select *
    into v_contact
    from public.client_contacts cc
   where cc.id = p_contact_id
     and cc.company_id = v_company_id
   for update;

  if not found then
    raise exception 'client_contact_not_found'
      using errcode = 'P0002';
  end if;

  if not public.current_app_user_can_update_client_row(v_contact.company_id, v_contact.client_id) then
    raise exception 'client_contact_write_permission_required'
      using errcode = '42501';
  end if;

  v_name := case
    when p_patch ? 'name' then trim(coalesce(p_patch->>'name', ''))
    else v_contact.name
  end;

  if v_name = '' then
    raise exception 'client_contact_name_required'
      using errcode = '22023';
  end if;

  v_status := case
    when p_patch ? 'status' then lower(trim(coalesce(p_patch->>'status', '')))
    else v_contact.status
  end;

  if v_status not in ('active', 'inactive') then
    raise exception 'invalid_client_contact_status'
      using errcode = '22023';
  end if;

  v_is_default := case
    when p_patch ? 'is_default' then coalesce((p_patch->>'is_default')::boolean, false)
    else v_contact.is_default
  end;

  if v_status <> 'active' then
    v_is_default := false;
  end if;

  if v_is_default then
    update public.client_contacts
       set is_default = false
     where company_id = v_contact.company_id
       and client_id = v_contact.client_id
       and id <> v_contact.id
       and is_default is true;
  end if;

  update public.client_contacts cc
     set name = v_name,
         title = case when p_patch ? 'title' then nullif(p_patch->>'title', '') else cc.title end,
         email = case when p_patch ? 'email' then nullif(p_patch->>'email', '') else cc.email end,
         phone = case when p_patch ? 'phone' then nullif(p_patch->>'phone', '') else cc.phone end,
         notes = case when p_patch ? 'notes' then nullif(p_patch->>'notes', '') else cc.notes end,
         status = v_status,
         is_default = v_is_default
   where cc.id = v_contact.id;

  return query
  select *
    from public.rpc_client_contact_list(v_contact.client_id) listed
   where listed.contact_id = v_contact.id;
end;
$$;

create or replace function public.rpc_client_contact_set_status(
  p_contact_id bigint,
  p_status text
)
returns table (
  contact_id bigint,
  company_id uuid,
  client_id bigint,
  name text,
  title text,
  email text,
  phone text,
  notes text,
  status text,
  is_default boolean,
  created_at timestamptz,
  updated_at timestamptz,
  created_by_user_id uuid
)
language sql
volatile
security definer
set search_path = public
as $$
  select *
    from public.rpc_client_contact_update(
      p_contact_id,
      jsonb_build_object('status', lower(trim(coalesce(p_status, ''))))
    );
$$;

create or replace function public.rpc_client_contact_set_default(
  p_contact_id bigint
)
returns table (
  contact_id bigint,
  company_id uuid,
  client_id bigint,
  name text,
  title text,
  email text,
  phone text,
  notes text,
  status text,
  is_default boolean,
  created_at timestamptz,
  updated_at timestamptz,
  created_by_user_id uuid
)
language sql
volatile
security definer
set search_path = public
as $$
  select *
    from public.rpc_client_contact_update(
      p_contact_id,
      jsonb_build_object('status', 'active', 'is_default', true)
    );
$$;

create or replace function public.rpc_create_order(payload jsonb)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_client_id bigint;
  v_managing_amc_id bigint;
  v_client_contact_id bigint;
  v_client_contact public.client_contacts%rowtype;
  v_manual text;
  v_appraiser uuid;
  v_company_id uuid;
  v_order_number text;
  v_row public.orders;
begin
  if not public.current_app_user_can_create_order() then
    raise exception 'not authorized to create orders'
      using errcode = '42501';
  end if;

  v_client_id := nullif(payload->>'client_id', '')::bigint;
  v_managing_amc_id := nullif(payload->>'managing_amc_id', '')::bigint;
  v_client_contact_id := nullif(payload->>'client_contact_id', '')::bigint;
  v_manual := coalesce(
    nullif(payload->>'manual_client', ''),
    nullif(payload->>'manual_client_name', '')
  );
  v_appraiser := nullif(payload->>'appraiser_id', '')::uuid;
  v_company_id := public.current_company_id();

  if v_client_id is not null
     and not public.current_app_user_can_attach_order_client(v_client_id) then
    raise exception 'client_id % is not attachable to orders in the current company', v_client_id
      using errcode = '42501';
  end if;

  if v_managing_amc_id is not null
     and not public.current_app_user_can_attach_order_amc(v_managing_amc_id) then
    raise exception 'managing_amc_id % is not an attachable current-company AMC client', v_managing_amc_id
      using errcode = '42501';
  end if;

  if v_client_contact_id is not null then
    if v_client_id is null then
      raise exception 'client_contact_requires_client'
        using errcode = '22023';
    end if;

    select *
      into v_client_contact
      from public.client_contacts cc
     where cc.id = v_client_contact_id
       and cc.company_id = v_company_id
       and cc.client_id = v_client_id
       and cc.status = 'active';

    if not found then
      raise exception 'client_contact_not_found'
        using errcode = 'P0002';
    end if;
  end if;

  v_order_number := public.next_order_number_v2(v_company_id, now());

  insert into public.orders (
    client_id, managing_amc_id, client_contact_id,
    client_contact_name, client_contact_title, client_contact_email, client_contact_phone,
    manual_client, manual_client_name, appraiser_id, order_number,
    property_address, city, state, postal_code,
    base_fee, appraiser_fee, appraiser_split, notes,
    status, created_at, updated_at
  ) values (
    v_client_id, v_managing_amc_id, v_client_contact_id,
    v_client_contact.name, v_client_contact.title, v_client_contact.email, v_client_contact.phone,
    v_manual, v_manual, v_appraiser, v_order_number,
    nullif(payload->>'property_address',''), nullif(payload->>'city',''), nullif(payload->>'state',''), nullif(payload->>'postal_code',''),
    nullif(payload->>'base_fee','')::numeric,
    nullif(payload->>'appraiser_fee','')::numeric,
    nullif(payload->>'appraiser_split','')::numeric,
    nullif(payload->>'notes',''),
    coalesce(nullif(payload->>'status',''),'new'),
    now(), now()
  )
  returning * into v_row;

  return v_row;
end;
$$;

create or replace function public.rpc_update_order(order_id uuid, patch jsonb)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_patch jsonb := coalesce(patch, '{}'::jsonb);
  has_client boolean := v_patch ? 'client_id';
  has_managing_amc boolean := v_patch ? 'managing_amc_id';
  has_client_contact boolean := v_patch ? 'client_contact_id';
  has_manual_client boolean := (v_patch ? 'manual_client') or (v_patch ? 'manual_client_name');
  has_appraiser boolean := v_patch ? 'appraiser_id';
  has_reviewer boolean := v_patch ? 'reviewer_id';
  has_property_address boolean := v_patch ? 'property_address';
  has_city boolean := v_patch ? 'city';
  has_state boolean := v_patch ? 'state';
  has_postal_code boolean := v_patch ? 'postal_code';
  has_base_fee boolean := v_patch ? 'base_fee';
  has_split_pct boolean := v_patch ? 'split_pct';
  has_appraiser_split boolean := v_patch ? 'appraiser_split';
  has_appraiser_fee boolean := v_patch ? 'appraiser_fee';
  has_property_type boolean := v_patch ? 'property_type';
  has_report_type boolean := v_patch ? 'report_type';
  has_entry_contact_name boolean := v_patch ? 'entry_contact_name';
  has_entry_contact_phone boolean := v_patch ? 'entry_contact_phone';
  has_site_visit_at boolean := v_patch ? 'site_visit_at';
  has_review_due_at boolean := v_patch ? 'review_due_at';
  has_final_due_at boolean := v_patch ? 'final_due_at';
  has_notes boolean := v_patch ? 'notes';
  in_client text := v_patch->>'client_id';
  in_managing_amc text := v_patch->>'managing_amc_id';
  in_client_contact text := v_patch->>'client_contact_id';
  v_client_id bigint;
  v_managing_amc_id bigint;
  v_client_contact_id bigint;
  v_client_contact public.client_contacts%rowtype;
  v_manual text := coalesce(
    v_patch->>'manual_client_name',
    v_patch->>'manual_client'
  );
  v_split numeric;
  v_existing public.orders;
  v_target_client_id bigint;
  v_clear_client_contact boolean := false;
  v_row public.orders;
begin
  if jsonb_typeof(v_patch) <> 'object' then
    raise exception 'order update patch must be a JSON object'
      using errcode = '22023';
  end if;

  if v_patch ? 'order_number' then
    raise exception 'generic order update RPCs do not accept order_number; use rpc_order_number_override'
      using errcode = '22023';
  end if;

  if v_patch ? 'client_contact_name'
     or v_patch ? 'client_contact_title'
     or v_patch ? 'client_contact_email'
     or v_patch ? 'client_contact_phone' then
    raise exception 'client contact snapshot fields are server-managed'
      using errcode = '22023';
  end if;

  select *
    into v_existing
    from public.orders
   where id = order_id;

  if not found then
    raise exception 'order not found';
  end if;

  if not public.current_app_user_can_update_order_row(
    v_existing.company_id,
    v_existing.appraiser_id,
    v_existing.assigned_to,
    v_existing.reviewer_id,
    v_existing.status
  ) then
    raise exception 'not authorized to update order %', order_id
      using errcode = '42501';
  end if;

  if has_client then
    v_client_id := nullif(in_client, '')::bigint;
    if v_client_id is not null
       and not public.current_app_user_can_attach_order_client(v_client_id) then
      raise exception 'client_id % is not attachable to orders in the current company', v_client_id
        using errcode = '42501';
    end if;
  end if;

  if has_managing_amc then
    v_managing_amc_id := nullif(in_managing_amc, '')::bigint;
    if v_managing_amc_id is not null
       and not public.current_app_user_can_attach_order_amc(v_managing_amc_id) then
      raise exception 'managing_amc_id % is not an attachable current-company AMC client', v_managing_amc_id
        using errcode = '42501';
    end if;
  end if;

  v_target_client_id := case when has_client then v_client_id else v_existing.client_id end;

  if has_client_contact then
    v_client_contact_id := nullif(in_client_contact, '')::bigint;

    if v_client_contact_id is not null then
      if v_target_client_id is null then
        raise exception 'client_contact_requires_client'
          using errcode = '22023';
      end if;

      select *
        into v_client_contact
        from public.client_contacts cc
       where cc.id = v_client_contact_id
         and cc.company_id = v_existing.company_id
         and cc.client_id = v_target_client_id
         and cc.status = 'active';

      if not found then
        raise exception 'client_contact_not_found'
          using errcode = 'P0002';
      end if;
    end if;
  elsif has_client and v_client_id is distinct from v_existing.client_id then
    v_clear_client_contact := true;
  end if;

  if has_split_pct then
    v_split := nullif(v_patch->>'split_pct', '')::numeric;
  elsif has_appraiser_split then
    v_split := nullif(v_patch->>'appraiser_split', '')::numeric;
  end if;

  update public.orders
     set client_id        = case when has_client then v_client_id else client_id end,
         managing_amc_id  = case when has_managing_amc then v_managing_amc_id else managing_amc_id end,
         client_contact_id = case
           when has_client_contact then v_client_contact_id
           when v_clear_client_contact then null
           else client_contact_id
         end,
         client_contact_name = case
           when has_client_contact and v_client_contact_id is not null then v_client_contact.name
           when has_client_contact or v_clear_client_contact then null
           else client_contact_name
         end,
         client_contact_title = case
           when has_client_contact and v_client_contact_id is not null then v_client_contact.title
           when has_client_contact or v_clear_client_contact then null
           else client_contact_title
         end,
         client_contact_email = case
           when has_client_contact and v_client_contact_id is not null then v_client_contact.email
           when has_client_contact or v_clear_client_contact then null
           else client_contact_email
         end,
         client_contact_phone = case
           when has_client_contact and v_client_contact_id is not null then v_client_contact.phone
           when has_client_contact or v_clear_client_contact then null
           else client_contact_phone
         end,
         manual_client    = case when has_manual_client then nullif(v_manual, '') else manual_client end,
         manual_client_name = case when has_manual_client then nullif(v_manual, '') else manual_client_name end,
         appraiser_id     = case when has_appraiser then nullif(v_patch->>'appraiser_id', '')::uuid else appraiser_id end,
         reviewer_id      = case when has_reviewer then nullif(v_patch->>'reviewer_id', '')::uuid else reviewer_id end,
         property_address = case when has_property_address then nullif(v_patch->>'property_address', '') else property_address end,
         city             = case when has_city then nullif(v_patch->>'city', '') else city end,
         state            = case when has_state then nullif(v_patch->>'state', '') else state end,
         postal_code      = case when has_postal_code then nullif(v_patch->>'postal_code', '') else postal_code end,
         base_fee         = case when has_base_fee then nullif(v_patch->>'base_fee', '')::numeric else base_fee end,
         appraiser_fee    = case when has_appraiser_fee then nullif(v_patch->>'appraiser_fee', '')::numeric else appraiser_fee end,
         split_pct        = case when has_split_pct or has_appraiser_split then v_split else split_pct end,
         appraiser_split  = case when has_split_pct or has_appraiser_split then v_split else appraiser_split end,
         property_type    = case when has_property_type then nullif(v_patch->>'property_type', '') else property_type end,
         report_type      = case when has_report_type then nullif(v_patch->>'report_type', '') else report_type end,
         entry_contact_name = case when has_entry_contact_name then nullif(v_patch->>'entry_contact_name', '') else entry_contact_name end,
         entry_contact_phone = case when has_entry_contact_phone then nullif(v_patch->>'entry_contact_phone', '') else entry_contact_phone end,
         site_visit_at    = case when has_site_visit_at then nullif(v_patch->>'site_visit_at', '')::timestamp else site_visit_at end,
         review_due_at    = case when has_review_due_at then nullif(v_patch->>'review_due_at', '')::timestamptz else review_due_at end,
         final_due_at     = case when has_final_due_at then nullif(v_patch->>'final_due_at', '')::timestamptz else final_due_at end,
         notes            = case when has_notes then nullif(v_patch->>'notes', '') else notes end,
         updated_at       = now()
   where id = order_id
  returning * into v_row;

  return v_row;
end;
$$;

drop view if exists public.v_orders_active_frontend_v4;

create or replace view public.v_orders_frontend_v4 as
select
  o.id,
  o.id as order_id,
  o.company_id,
  o.order_number,
  o.order_number as order_no,

  coalesce(c.name, o.manual_client, o.manual_client_name) as client_name,
  o.client_id,
  o.amc_id,
  o.managing_amc_id,
  coalesce(mamc.name, amc.name) as amc_name,
  coalesce(o.appraiser_id, o.assigned_to) as assigned_appraiser_id,
  coalesce(o.manual_appraiser, ua.display_name, ua.full_name, ua.name) as assigned_appraiser_name,
  o.assigned_to,
  o.appraiser_id,
  o.reviewer_id,
  coalesce(o.manual_appraiser, ua.display_name, ua.full_name, ua.name) as appraiser_name,
  coalesce(ur.display_name, ur.full_name, ur.name) as reviewer_name,
  coalesce(ua.color, ua.display_color) as appraiser_color,
  coalesce(ur.color, ur.display_color) as reviewer_color,

  coalesce(o.property_address, o.address) as address_line1,
  coalesce(o.property_address, o.address) as address,
  coalesce(o.order_number, o.title) as display_title,
  coalesce(o.property_address, o.address) as display_subtitle,
  o.city,
  o.state,
  coalesce(o.postal_code, o.zip) as postal_code,
  coalesce(o.postal_code, o.zip) as zip,
  o.property_type,
  o.report_type,

  coalesce(o.fee_amount, o.base_fee) as fee_amount,
  coalesce(o.fee_amount, o.base_fee) as fee,
  o.base_fee,
  o.appraiser_fee,
  coalesce(o.split_pct, o.appraiser_split) as split_pct,

  coalesce(
    o.site_visit_at,
    (o.site_visit_date)::timestamptz,
    (o.inspection_date)::timestamptz
  ) as site_visit_at,
  coalesce(
    o.site_visit_at,
    (o.site_visit_date)::timestamptz,
    (o.inspection_date)::timestamptz
  ) as site_visit_date,
  coalesce(
    o.review_due_at,
    (o.due_for_review)::timestamptz,
    (o.review_due_date)::timestamptz
  ) as review_due_at,
  coalesce(
    o.review_due_at,
    (o.due_for_review)::timestamptz,
    (o.review_due_date)::timestamptz
  ) as review_due_date,
  coalesce(
    o.final_due_at,
    o.client_due_at,
    (o.due_to_client)::timestamptz,
    (o.due_date)::timestamptz
  ) as final_due_at,
  coalesce(
    o.final_due_at,
    o.client_due_at,
    (o.due_to_client)::timestamptz,
    (o.due_date)::timestamptz
  ) as final_due_date,
  coalesce(
    o.final_due_at,
    o.client_due_at,
    (o.due_to_client)::timestamptz,
    (o.due_date)::timestamptz
  ) as due_date,

  o.status,
  o.created_at,
  o.updated_at,
  o.date_ordered,
  coalesce(o.is_archived, o.archived, false) as is_archived,
  o.property_contact_name,
  o.property_contact_phone,
  o.entry_contact_name,
  o.entry_contact_phone,
  o.access_notes,
  o.notes,
  a.last_activity_at,
  o.client_contact_id,
  o.client_contact_name,
  o.client_contact_title,
  o.client_contact_email,
  o.client_contact_phone
from public.orders o
left join public.clients c on c.id = o.client_id
left join public.clients mamc on mamc.id = o.managing_amc_id
left join public.amcs amc on amc.id = o.amc_id
left join public.users ua on ua.id = o.appraiser_id
left join public.users ur on ur.id = o.reviewer_id
left join lateral (
  select max(al.created_at) as last_activity_at
    from public.activity_log al
   where al.order_id = o.id
) a on true;

create or replace view public.v_orders_active_frontend_v4 as
select *
from public.v_orders_frontend_v4
where lower(coalesce(status::text, '')) not in ('completed', 'complete', 'cancelled', 'canceled');

grant select on public.v_orders_frontend_v4 to authenticated;
grant select on public.v_orders_frontend_v4 to anon;
grant select on public.v_orders_active_frontend_v4 to authenticated;
grant select on public.v_orders_active_frontend_v4 to anon;

alter view public.v_orders_frontend_v4 set (security_invoker = false);
alter view public.v_orders_active_frontend_v4 set (security_invoker = false);

revoke all privileges on function public.rpc_client_contact_list(bigint) from public, anon;
revoke all privileges on function public.rpc_client_contact_create(bigint, jsonb) from public, anon;
revoke all privileges on function public.rpc_client_contact_update(bigint, jsonb) from public, anon;
revoke all privileges on function public.rpc_client_contact_set_status(bigint, text) from public, anon;
revoke all privileges on function public.rpc_client_contact_set_default(bigint) from public, anon;

grant execute on function public.rpc_client_contact_list(bigint) to authenticated, service_role;
grant execute on function public.rpc_client_contact_create(bigint, jsonb) to authenticated, service_role;
grant execute on function public.rpc_client_contact_update(bigint, jsonb) to authenticated, service_role;
grant execute on function public.rpc_client_contact_set_status(bigint, text) to authenticated, service_role;
grant execute on function public.rpc_client_contact_set_default(bigint) to authenticated, service_role;

grant execute on function public.rpc_create_order(jsonb) to authenticated;
grant execute on function public.rpc_update_order(uuid, jsonb) to authenticated;

comment on table public.client_contacts is
  'Reusable client/lender/AMC relationship contacts. Separate from property/access contacts used for inspection logistics.';

comment on column public.orders.client_contact_id is
  'Selected reusable client relationship contact for this order, if any.';

comment on column public.orders.client_contact_name is
  'Server-side snapshot of the selected client relationship contact name at order create/update time.';

comment on column public.orders.client_contact_title is
  'Server-side snapshot of the selected client relationship contact title at order create/update time.';

comment on column public.orders.client_contact_email is
  'Server-side snapshot of the selected client relationship contact email at order create/update time.';

comment on column public.orders.client_contact_phone is
  'Server-side snapshot of the selected client relationship contact phone at order create/update time.';

comment on function public.rpc_client_contact_list(bigint) is
  'Lists reusable client relationship contacts for a readable current-company client.';

comment on function public.rpc_client_contact_create(bigint, jsonb) is
  'Creates a reusable client relationship contact for a current-company client the caller can update.';

comment on function public.rpc_client_contact_update(bigint, jsonb) is
  'Updates reusable client relationship contact metadata for a client the caller can update.';

comment on function public.rpc_client_contact_set_status(bigint, text) is
  'Activates or deactivates a reusable client relationship contact.';

comment on function public.rpc_client_contact_set_default(bigint) is
  'Marks one active reusable client relationship contact as the default for its client.';

comment on function public.rpc_create_order(jsonb) is
  'Guarded order creation RPC. Generates order number server-side and snapshots selected client relationship contact fields when payload.client_contact_id is provided.';

comment on function public.rpc_update_order(uuid, jsonb) is
  'Generic order update RPC with explicit allowlist. Supports server-managed client relationship contact snapshots through payload.client_contact_id.';

commit;
